###
GET http://localhost:3000/products
###
GET http://localhost:3000/products/d2ff3048-83bc-425a-8ad3-d6d9af1c7c6d

###
GET http://localhost:3000/products?order=newest&limit=2&offset=0&name=조던

###
GET http://localhost:3000/products?order=newest&limit=2&offset=0&description=미개봉

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "고급 도마",
    "description": "무게감 있고 이름있는 고급 도마입니다.",
    "price": 50000,
    "tag": "KITCHENWARE"
  }

###
PATCH http://localhost:3000/products/19b65fb9-6e5d-43cd-92bc-29036af7b6d
Content-Type: application/json

{
    "name": "손흥민 싸인 축구공",
    "description": "토트넘 경기가서 받아온 손흥민 싸인 축구공입니다.",
    "price": 300000,
    "tag": "SPORTS"
  }

###
DELETE http://localhost:3000/products/9729752d-bda0-4b66-8656-7c3a5c4455b7