### 게시글 등록
POST http://localhost:3000/board
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2NTE1NiwiZXhwIjoxNzQyODY4NzU2fQ.XTfxqg0t05GbxX-sv1WtLRtUAFmQkOeKs5IhTSF41TQ

{
  "title": "게시글 제목 입니다.",
  "description": "게시글 내용 입니다."
}

### 게시글 조회
GET http://localhost:3000/board/4

### 게시글 수정
PUT http://localhost:3000/board/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2NTE1NiwiZXhwIjoxNzQyODY4NzU2fQ.XTfxqg0t05GbxX-sv1WtLRtUAFmQkOeKs5IhTSF41TQ

{
  "title": "안녕하세요",
  "description": "안녕히가세요"
}

### 게시글 삭제
DELETE http://localhost:3000/board/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Mjg2NTE1NiwiZXhwIjoxNzQyODY4NzU2fQ.XTfxqg0t05GbxX-sv1WtLRtUAFmQkOeKs5IhTSF41TQ
