### 상품 등록
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Mjg5OTQyOSwiZXhwIjoxNzQyOTAzMDI5fQ.6Wl2khZrOsfWAZWiwMwZBtiIN4gDxN0TXkWS2wQECf0

{
  "name": "Mac 2",
  "price": 1000000
}

### 상품 조회
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Mjg5OTQyOSwiZXhwIjoxNzQyOTAzMDI5fQ.6Wl2khZrOsfWAZWiwMwZBtiIN4gDxN0TXkWS2wQECf0

### 상품 수정
PUT http://localhost:3000/products/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Mjg5OTQyOSwiZXhwIjoxNzQyOTAzMDI5fQ.6Wl2khZrOsfWAZWiwMwZBtiIN4gDxN0TXkWS2wQECf0

{
  "name": "Mac 5",
  "price": 1000000
}

### 상품 삭제
DELETE http://localhost:3000/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Mjg5OTQyOSwiZXhwIjoxNzQyOTAzMDI5fQ.6Wl2khZrOsfWAZWiwMwZBtiIN4gDxN0TXkWS2wQECf0
