### 모든 Article 가져오기
GET http://localhost:3000/articles?orderBy=recent

### 새로운 Article 만들기
POST http://localhost:3000/articles
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "title": "새로운 Article",
    "content": "이것은 새로운 Article의 내용입니다.",
    "image": "https://example.com/image.jpg"
}

### 특정 ID의 Article 가져오기
GET http://localhost:3000/articles/6

### Article 업데이트하기
PATCH http://localhost:3000/articles/7
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "title": "Article 업데이트",
    "content": "이것은 업데이트된 내용입니다."
}

### Article 삭제하기
DELETE http://localhost:3000/articles/2
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNTU2NTA2LCJleHAiOjE3NDM1NjAxMDZ9.8LCoOUYo8XHEgwG92OGcSptC6CjOPL5XfLkT5cDh6Ww; Max-Age=3600; Path=/; Expires=Wed, 02 Apr 2025 02:15:06 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNTU2NTA2LCJleHAiOjE3NDQxNjEzMDZ9.Tf74Npg7m9fj7ZPbVaK9nZUWS1vWYVQNKzg-VjsAQzc; Max-Age=604800; Path=/auth/refresh; Expires=Wed, 09 Apr 2025 01:15:06 GMT; HttpOnly


### Article 좋아요 테스트
POST http://localhost:3000/articles/7/likes
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly


### Article 좋아요 취소 테스트
DELETE http://localhost:3000/articles/6/likes
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNTU2NTA2LCJleHAiOjE3NDM1NjAxMDZ9.8LCoOUYo8XHEgwG92OGcSptC6CjOPL5XfLkT5cDh6Ww; Max-Age=3600; Path=/; Expires=Wed, 02 Apr 2025 02:15:06 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNTU2NTA2LCJleHAiOjE3NDQxNjEzMDZ9.Tf74Npg7m9fj7ZPbVaK9nZUWS1vWYVQNKzg-VjsAQzc; Max-Age=604800; Path=/auth/refresh; Expires=Wed, 09 Apr 2025 01:15:06 GMT; HttpOnly



### Article에 Comment 달기 테스트
POST http://localhost:3000/articles/6/comments
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "content": "이것은 Article에 대한 테스트 Comment입니다."
}

### Article의 Comment 가져오기 테스트
GET http://localhost:3000/articles/6/comments?limit=200

### Comment 업데이트 테스트
PATCH http://localhost:3000/comments/5
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNTY2MzQ3LCJleHAiOjE3NDM1Njk5NDd9.fA4hTJ2XpBhY6hIwM2OYiP9sf55bvmAkM0P2wWxmd9E; Max-Age=3600; Path=/; Expires=Wed, 02 Apr 2025 04:59:07 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzNTY2MzQ3LCJleHAiOjE3NDQxNzExNDd9.8JvKWcWfpbp-oE6xaHbrPHD0ukuMkblht2nxaamJIxw; Max-Age=604800; Path=/auth/refresh; Expires=Wed, 09 Apr 2025 03:59:07 GMT; HttpOnly

{
    "content": "이것은 업데이트된 테스트 Comment입니다."
}

### Comment 삭제 테스트
DELETE http://localhost:3000/comments/1

### 새로운 Product 만들기 테스트
POST http://localhost:3000/products
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "name": "테스트 Product",
    "description": "이것은 테스트 Product 설명입니다.",
    "price": 100,
    "tags": [],
    "images": ["image1.png", "image2.png"]
}

### 모든 Product 가져오기 테스트
GET http://localhost:3000/products

### 특정 ID의 Product 가져오기 테스트
GET http://localhost:3000/products/4

### Product 업데이트하기 테스트
PATCH http://localhost:3000/products/5
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "name": "업데이트된 테스트 Product",
    "description": "이것은 업데이트된 테스트 Product 설명입니다.",
    "price": 150,
    "tags": ["업데이트", "Product"],
    "images": ["업데이트된_image1.png"]
}

### Product 삭제하기 테스트
DELETE http://localhost:3000/products/2

### Product 좋아요 테스트
POST http://localhost:3000/products/4/favorites
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNTc2MTY0LCJleHAiOjE3NDM1Nzk3NjR9.8a_7GrJZxNhs6ubNZp4GmGqB85JJxvs3vmARRplmspc; Max-Age=3600; Path=/; Expires=Wed, 02 Apr 2025 07:42:44 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNTc2MTY0LCJleHAiOjE3NDQxODA5NjR9.ZUMqzGlP8qU2PT-SVh2FU4IcWZ_FdX6l98j8DZIblP4; Max-Age=604800; Path=/auth/refresh; Expires=Wed, 09 Apr 2025 06:42:44 GMT; HttpOnly


### Product 좋아요 취소 테스트
DELETE http://localhost:3000/products/1/favorites


### Product에 Comment 달기 테스트
POST http://localhost:3000/products/2/comments
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNTcxNDk5LCJleHAiOjE3NDM1NzUwOTl9.S9mzt_kIoZ1vmmp0Lndxv8aBeF0P6MVoXBa_cubyYFA; Max-Age=3600; Path=/; Expires=Wed, 02 Apr 2025 06:24:59 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNTcxNDk5LCJleHAiOjE3NDQxNzYyOTl9.fi7djYZPps08USEvex4DpUoK9Qm7iN4r0nEd0QiZpJU; Max-Age=604800; Path=/auth/refresh; Expires=Wed, 09 Apr 2025 05:24:59 GMT; HttpOnly

{
    "content": "이것은 Product에 대한 테스트 Comment입니다."
}

### Product의 Comment 가져오기 테스트
GET http://localhost:3000/products/1/comments?limit=5


### Product의 Comment 가져오기 테스트 (Cursor)
GET http://localhost:3000/products/1/comments?cursor=1&limit=5


### Comment 업데이트하기 테스트
PATCH http://localhost:3000/comments/2
Content-Type: application/json

{
    "content": "이것은 업데이트된 테스트 Comment입니다."
}

### Comment 삭제하기 테스트
DELETE http://localhost:3000/comments/2

### 이미지 업로드 테스트
POST http://localhost:3000/images/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 회원가입 테스트
POST http://localhost:3000/auth/register
Content-Type: application/json

{

    "email": "testuser111@example.com",
    "nickname": "testuser1",
    "password": "testpassword"
}

### 로그인 테스트
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "testuser1@example.com",
    "password": "newtestpassword"
}

### 로그아웃 테스트
POST http://localhost:3000/auth/logout

### 토큰 갱신 테스트
POST http://localhost:3000/auth/refresh
Cookie: refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzQzNTc5MjY0LCJleHAiOjE3NDQxODQwNjR9.QNZfQpStINiCYPyFNbhXwiIVFYBsV0HIyBa7pch5m-k


### 내 정보 가져오기 테스트
GET http://localhost:3000/users/me

### 내 정보 업데이트 테스트
PATCH http://localhost:3000/users/me
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "nickname": "testuser-edit"
}

### 내 비밀번호 업데이트 테스트
PATCH http://localhost:3000/users/me/password
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly

{
    "password": "newtestpassword",
    "newPassword": "newtestpassword1"
}

### 내 상품 목록 가져오기 테스트
GET http://localhost:3000/users/me/products?page=1&pageSize=5
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDM2Njc0Nzd9.cH37Fgu3CGIfepqnvPe0yQ5IDkqpNgywrtpCpUbLNNU; Max-Age=3600; Path=/; Expires=Thu, 03 Apr 2025 08:04:37 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQzNjYzODc3LCJleHAiOjE3NDQyNjg2Nzd9.R9Jol1ODMYY3oYcAdSF6zlrtb_ZFJ3jC21XNwog0fQI; Max-Age=604800; Path=/auth/refresh; Expires=Thu, 10 Apr 2025 07:04:37 GMT; HttpOnly


### 내 좋아요 목록 가져오기 테스트
GET http://localhost:3000/users/me/favorites?page=1&pageSize=5
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzQzNTc5MjgxLCJleHAiOjE3NDM1ODI4ODF9.nOzd4kTFr1PiXuznx0imE8bmxeMUp8I9GwYmtesOWrw; Max-Age=3600; Path=/; Expires=Wed, 02 Apr 2025 08:34:41 GMT; HttpOnly,refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzQzNTc5MjgxLCJleHAiOjE3NDQxODQwODF9.uF6ZUgtFT1z6Yjsgb4pkM3AMEd2TIOgdzs3mmHfuuqA; Max-Age=604800; Path=/auth/refresh; Expires=Wed, 09 Apr 2025 07:34:41 GMT; HttpOnly

