CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "nickname" varchar UNIQUE,
  "password" varchar,
  "image" varchar,
  "create_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_date" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "articles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "title" varchar,
  "content" varchar,
  "image" varchar,
  "create_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_date" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "name" varchar(10),
  "description" varchar,
  "price" int,
  "tags" varchar[],
  "image" varchar[],
  "create_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_date" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "article_id" int,
  "user_id" int NOT NULL,
  "content" varchar,
  "create_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_date" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "article_likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "article_id" int NOT NULL,
  "create_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_date" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "product_likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "create_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_date" timestamp DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "users"."create_date" IS 'default: CURRENT_TIMESTAMP';

COMMENT ON COLUMN "users"."update_date" IS 'default: CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP';

COMMENT ON COLUMN "articles"."create_date" IS 'default: CURRENT_TIMESTAMP';

COMMENT ON COLUMN "articles"."update_date" IS 'default: CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP';

COMMENT ON COLUMN "products"."create_date" IS 'default: CURRENT_TIMESTAMP';

COMMENT ON COLUMN "products"."update_date" IS 'default: CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP';

COMMENT ON COLUMN "comments"."create_date" IS 'default: CURRENT_TIMESTAMP';

COMMENT ON COLUMN "comments"."update_date" IS 'default: CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP';

COMMENT ON COLUMN "article_likes"."create_date" IS 'default: CURRENT_TIMESTAMP';

COMMENT ON COLUMN "article_likes"."update_date" IS 'default: CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP';

COMMENT ON COLUMN "product_likes"."create_date" IS 'default: CURRENT_TIMESTAMP';

COMMENT ON COLUMN "product_likes"."update_date" IS 'default: CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP';

ALTER TABLE "articles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "product_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "article_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id");

ALTER TABLE "product_likes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "article_likes" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id");
