### 아티클 생성
POST http://localhost:3000/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8

{
  "title": "새로운 아티클 제목",
  "content": "아티클 내용입니다."
}


### 아티클 조회 
GET http://localhost:3000/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8



### 아티클 수정
PUT http://localhost:3000/article/2 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8

{
  "title": "수정된 아티클 제목",
  "content": "수정된 아티클 내용입니다."
}



### 아티클 삭제
DELETE http://localhost:3000/article/1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8

