### 댓글 생성
POST http://localhost:3000/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzE2NzE0NCwiZXhwIjoxNzQzMTcwNzQ0fQ.9d635aFnOREDO7BZhJpWtKM4GoZ5y7YsFYMeH27dLIM

{
  "type": "board",
  "id": 1,
  "title": "게시판 최고",
  "description": "좋은 게시판",
  "rating": 5
}

### 댓글 리스트
GET http://localhost:3000/comment

### 댓글 
GET http://localhost:3000/comment/2

### 댓글 수정
PUT http://localhost:3000/comment/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzE2NzE0NCwiZXhwIjoxNzQzMTcwNzQ0fQ.9d635aFnOREDO7BZhJpWtKM4GoZ5y7YsFYMeH27dLIM

{
  "title": "게시판 최고!!",
  "description": "좋은 게시판",
  "rating": 5
}

### 댓글 삭제
DELETE http://localhost:3000/comment/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzE2NzE0NCwiZXhwIjoxNzQzMTcwNzQ0fQ.9d635aFnOREDO7BZhJpWtKM4GoZ5y7YsFYMeH27dLIM
