### 상품 등록
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8

{
  "name": "고급 도마",
    "description": "무게감 있고 이름있는 고급 도마입니다.",
    "price": 50000,
    "tag": "KITCHENWARE"
}

### 상품 조회
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8

### 상품 수정
PUT http://localhost:3000/products/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8

{
  "name": "고급 도마",
    "description": "무게감 있고 이름있는 고급 도마입니다.",
    "price": 500000,
    "tag": "KITCHENWARE"
}

### 상품 삭제
DELETE http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MzQ2NjYxMCwiZXhwIjoxNzQzNDcwMjEwfQ.3zMACVc6deoLP7BV_NAChDPOaUfee_PpKouUuwkstc8
